on:
  push:
    branches:
      - main
      - master
permissions:
  contents: read

name: "check package on main with project conventions"

jobs:
  check-package:
    uses: ./.github/workflows/project_checks.yml
    secrets: inherit
