on:
  push:
    branches-ignore:
      - main
      - master
      - ghpages

name: "check package with project conventions"

jobs:
  check-package:
    uses: ./.github/workflows/project_checks.yml
    secrets: inherit
